/** Fichiers dans `marche-dore/assets/images/catalog`, servis via `/catalog/media/:id`. */
export const CATEGORY_ART: Record<string, string> = {
  'fruits-legumes': 'cat-fruits',
  viandes: 'cat-viandes',
  charcuterie: 'cat-viandes',
  poissons: 'cat-poissons',
  surgeles: 'glace-assortiment',
  laitiers: 'cat-laitiers',
  oeufs: 'poulet',
  boulangerie: 'cat-boulangerie',
  'petit-dej': 'miel',
  'cafe-the': 'glace-cafe',
  feculents: 'cuisine-riz',
  huiles: 'cat-epicerie',
  epices: 'circle-epices',
  conserves: 'cat-poissons',
  epicerie: 'cat-epicerie',
  snacking: 'plantains',
  boissons: 'cat-boissons',
  alcools: 'cat-boissons',
  bio: 'cat-fruits',
  cuisine: 'cat-cuisine',
  glaces: 'cat-glaces',
  hygiene: 'cat-hygiene',
  maison: 'cat-maison',
  bebe: 'cat-bebe',
  animalerie: 'cat-maison',
};
